#!/usr/bin/env python3
"""
Adiciona um novo tipo de lançamento ao sistema.

O que este script faz:
  1. Atualiza o ENUM no banco de dados MySQL (via Docker ou conexão direta)
  2. Atualiza src/types.ts (EntryType e ENTRY_TYPES)
  3. Atualiza database/full_setup.sql
  4. Atualiza database/migrations/001_create_tables.sql
  5. Cria uma nova migration SQL numerada automaticamente

Uso:
  python3 add_entry_type.py
"""

import re
import subprocess
import sys
from datetime import date
from pathlib import Path

# Caminhos relativos à raiz do projeto (mesmo diretório deste script)
ROOT = Path(__file__).parent
TYPES_TS = ROOT / "src" / "types.ts"
FULL_SETUP_SQL = ROOT / "database" / "full_setup.sql"
CREATE_TABLES_SQL = ROOT / "database" / "migrations" / "001_create_tables.sql"
MIGRATIONS_DIR = ROOT / "database" / "migrations"

# Configuração do banco (lida do .env se existir)
def load_env():
    env = {"DB_HOST": "localhost", "DB_USER": "root", "DB_PASSWORD": "", "DB_NAME": "folhaponto_db"}
    env_file = ROOT / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                if key.strip() in env:
                    env[key.strip()] = value.strip()
    return env

# --- Leitura do types.ts ---

def read_current_types():
    text = TYPES_TS.read_text()

    # Extrai valores do EntryType union
    match = re.search(r"export type EntryType = (.+?);", text, re.DOTALL)
    if not match:
        sys.exit("Erro: EntryType não encontrado em types.ts")
    type_values = re.findall(r"'([^']+)'", match.group(1))

    return type_values, text

# --- Atualização do types.ts ---

def update_types_ts(value: str, label: str, type_values: list, text: str):
    # Adiciona ao EntryType union
    old_union = re.search(r"(export type EntryType = .+?;)", text, re.DOTALL).group(1)
    new_types = type_values + [value]
    new_union = "export type EntryType = " + " | ".join(f"'{v}'" for v in new_types) + ";"
    text = text.replace(old_union, new_union)

    # Adiciona ao ENTRY_TYPES: garante vírgula na última entrada existente e insere o novo item
    new_entry = f"  {{ value: '{value}', label: '{label}' }}"
    # Adiciona vírgula na última linha que termina com '}' sem vírgula, depois insere o novo item antes de '];'
    text = re.sub(r"(\})\s*\n(\];)$", f"\\1,\n{new_entry}\n\\2", text, flags=re.MULTILINE)

    TYPES_TS.write_text(text)
    print(f"  [OK] src/types.ts atualizado")

# --- Helpers para atualizar ENUMs nos SQLs ---

ENUM_PATTERN_FULL_SETUP = re.compile(
    r"(enum\('[^)]+)\)(\s+COLLATE utf8mb4_unicode_ci(?:\s+NOT NULL DEFAULT 'TRABALHO'|\s+DEFAULT NULL))"
)

def add_to_enum_full_setup(text: str, value: str) -> str:
    def replacer(m):
        current = m.group(1)
        if f"'{value}'" in current:
            return m.group(0)
        return current + f",'{value}')" + m.group(2)
    return ENUM_PATTERN_FULL_SETUP.sub(replacer, text)

ENUM_PATTERN_001 = re.compile(
    r"(tipo(?:_turno2)?\s+ENUM\([^)]+)\)(\s+(?:NOT NULL DEFAULT 'TRABALHO'|NULL),?)"
)

def add_to_enum_001(text: str, value: str) -> str:
    def replacer(m):
        current = m.group(1)
        if f"'{value}'" in current:
            return m.group(0)
        return current + f", '{value}')" + m.group(2)
    return ENUM_PATTERN_001.sub(replacer, text)

# --- Criação da migration ---

def next_migration_number() -> str:
    existing = [f.name for f in MIGRATIONS_DIR.glob("[0-9][0-9][0-9]_*.sql")]
    if not existing:
        return "005"
    nums = [int(f[:3]) for f in existing]
    return str(max(nums) + 1).zfill(3)

def create_migration(value: str) -> Path:
    num = next_migration_number()
    slug = value.lower().replace(" ", "_").replace(".", "")
    filename = MIGRATIONS_DIR / f"{num}_add_type_{slug}.sql"
    sql = f"""-- Migration {num}: Add '{value}' to tipo ENUM
-- Generated by add_entry_type.py on {date.today()}

ALTER TABLE lancamentos_diarios
  MODIFY COLUMN tipo ENUM(
    SELECT COLUMN_TYPE FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'lancamentos_diarios'
      AND COLUMN_NAME = 'tipo'
  );

-- Forma direta (execute manualmente se o ALTER acima falhar):
-- Copie o ENUM atual do banco e adicione '{value}' no final.
"""
    # Forma direta gerada com os valores atuais lidos do 001
    text_001 = CREATE_TABLES_SQL.read_text()
    match = re.search(r"tipo ENUM\(([^)]+)\)", text_001)
    if match:
        enum_vals = match.group(1).strip()
        # O valor já foi adicionado ao 001, então o enum_vals já inclui o novo
        sql = f"""-- Migration {num}: Add '{value}' to tipo ENUM
-- Generated by add_entry_type.py on {date.today()}

ALTER TABLE lancamentos_diarios
  MODIFY COLUMN tipo ENUM(
    {enum_vals}
  ) NOT NULL DEFAULT 'TRABALHO',
  MODIFY COLUMN tipo_turno2 ENUM(
    {enum_vals}
  ) NULL;
"""
    filename.write_text(sql)
    print(f"  [OK] Migration criada: database/migrations/{filename.name}")
    return filename

# --- Execução no banco ---

def find_docker_container() -> str | None:
    try:
        result = subprocess.run(
            ["docker", "ps", "--format", "{{.Names}}"],
            capture_output=True, text=True, timeout=5
        )
        for name in result.stdout.splitlines():
            if "mysql" in name.lower():
                return name
    except Exception:
        pass
    return None

def apply_migration(migration_file: Path, env: dict):
    container = find_docker_container()

    if container:
        print(f"  Aplicando via Docker (container: {container})...")
        cmd = [
            "docker", "exec", "-i", container,
            "mysql", "-u", env["DB_USER"], f"-p{env['DB_PASSWORD']}", env["DB_NAME"]
        ]
        with open(migration_file) as f:
            result = subprocess.run(cmd, stdin=f, capture_output=True, text=True)
        if result.returncode == 0:
            print("  [OK] Migration aplicada ao banco de dados")
        else:
            stderr = result.stderr.replace(f"-p{env['DB_PASSWORD']}", "-p****")
            print(f"  [ERRO] Falha ao aplicar migration:\n{stderr}")
            print(f"  Execute manualmente: docker exec -i {container} mysql -u {env['DB_USER']} -p {env['DB_NAME']} < {migration_file}")
    else:
        print("  Container MySQL Docker não encontrado.")
        print(f"  Execute a migration manualmente:\n    mysql -u {env['DB_USER']} -p {env['DB_NAME']} < {migration_file}")

# --- Main ---

def main():
    print("=" * 55)
    print("  Adicionar novo tipo de lançamento")
    print("=" * 55)

    type_values, ts_text = read_current_types()

    print("\nTipos existentes:")
    for i, v in enumerate(type_values, 1):
        print(f"  {i:2}. {v}")

    print()
    value = input("Valor do novo tipo (ex: SUSPENSAO): ").strip().upper()
    if not value:
        sys.exit("Valor não pode ser vazio.")
    if value in type_values:
        sys.exit(f"Tipo '{value}' já existe.")

    label = input(f"Label exibido na interface (ex: SUSPENSÃO): ").strip().upper()
    if not label:
        label = value

    print(f"\nNovo tipo: value='{value}' | label='{label}'")
    confirm = input("Confirmar? (s/N): ").strip().lower()
    if confirm != "s":
        sys.exit("Cancelado.")

    print("\nAtualizando arquivos...")

    # 1. types.ts
    update_types_ts(value, label, type_values, ts_text)

    # 2. full_setup.sql
    text = FULL_SETUP_SQL.read_text()
    FULL_SETUP_SQL.write_text(add_to_enum_full_setup(text, value))
    print("  [OK] database/full_setup.sql atualizado")

    # 3. 001_create_tables.sql
    text = CREATE_TABLES_SQL.read_text()
    CREATE_TABLES_SQL.write_text(add_to_enum_001(text, value))
    print("  [OK] database/migrations/001_create_tables.sql atualizado")

    # 4. Migration
    migration_file = create_migration(value)

    # 5. Banco de dados
    print("\nAplicando ao banco de dados...")
    env = load_env()
    apply_migration(migration_file, env)

    print("\nConcluído! Reinicie o backend se estiver em execução.")

if __name__ == "__main__":
    main()
