-- Migration 007: Add 'LIC. ACOMP. PESSOA DOENTE', 'AFAST DOACAO SANGUE ART 62', 'ABONO DE PONTO BIMESTRAL LEI' to tipo ENUM
-- Generated on 2026-04-25

ALTER TABLE lancamentos_diarios
  MODIFY COLUMN tipo ENUM(
    'TRABALHO', 'FERIAS', 'RECESSO', 'ATESTADO', 'LICENCA', 'FALTA', 'TRE', 'ABONO', 'CPIP', 'CURSO', 'ABONO_NIVER', 'FERIADO', 'ABONO DE PONTO ART 151 LEI', 'FALTA PARALISAÇÃO', 'ATESTADO DE COMPARECIMENTO', 'AFAST DOACAO SANGUE ART 62', 'LIC. ACOMP. PESSOA DOENTE', 'ABONO DE PONTO BIMESTRAL LEI'
  ) NOT NULL DEFAULT 'TRABALHO',
  MODIFY COLUMN tipo_turno2 ENUM(
    'TRABALHO', 'FERIAS', 'RECESSO', 'ATESTADO', 'LICENCA', 'FALTA', 'TRE', 'ABONO', 'CPIP', 'CURSO', 'ABONO_NIVER', 'FERIADO', 'ABONO DE PONTO ART 151 LEI', 'FALTA PARALISAÇÃO', 'ATESTADO DE COMPARECIMENTO', 'AFAST DOACAO SANGUE ART 62', 'LIC. ACOMP. PESSOA DOENTE', 'ABONO DE PONTO BIMESTRAL LEI'
  ) NULL;
