-- Migration 013: Add 'AFAST CASAMENTO ART 62 LEI' to tipo ENUM
-- Generated by add_entry_type.py on 2026-06-09

ALTER TABLE lancamentos_diarios
  MODIFY COLUMN tipo ENUM(
    SELECT COLUMN_TYPE FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'lancamentos_diarios'
      AND COLUMN_NAME = 'tipo'
  );

-- Forma direta (execute manualmente se o ALTER acima falhar):
-- Copie o ENUM atual do banco e adicione 'AFAST CASAMENTO ART 62 LEI' no final.
