#!/usr/bin/env python3
"""
Adiciona um novo tipo de lançamento ao sistema.

O que este script faz:
  1. Atualiza src/types.ts (EntryType e ENTRY_TYPES)
  2. Atualiza database/full_setup.sql (insere em tipos_lancamento)
  3. Cria uma nova migration SQL numerada automaticamente com INSERT IGNORE

Uso:
  python3 add_entry_type.py
"""

import re
import subprocess
import sys
from datetime import date
from pathlib import Path

# Caminhos relativos à raiz do projeto (mesmo diretório deste script)
ROOT = Path(__file__).parent.parent
TYPES_TS = ROOT / "src" / "types.ts"
FULL_SETUP_SQL = ROOT / "database" / "full_setup.sql"
CREATE_TABLES_SQL = ROOT / "database" / "migrations" / "001_create_tables.sql"
MIGRATIONS_DIR = ROOT / "database" / "migrations"

# Configuração do banco (lida do .env, com fallback para variáveis de ambiente)
def load_env():
    import os
    env = {
        "DB_HOST": "localhost",
        "DB_PORT": "3307",
        "DB_USER": "root",
        "DB_PASSWORD": "123456",
        "DB_NAME": "folhaponto_db",
    }
    env_file = ROOT / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                key = key.strip()
                if key in env:
                    value = value.strip()
                    # Remover aspas ao redor do valor (simples ou duplas)
                    if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
                        value = value[1:-1]
                    env[key] = value
    # Variáveis de ambiente do SO sobrescrevem o .env (útil em Docker/produção)
    for key in list(env.keys()):
        if key in os.environ and os.environ[key]:
            env[key] = os.environ[key]
    return env

# --- Leitura do types.ts ---

def read_current_types():
    text = TYPES_TS.read_text()

    # Extrai valores do EntryType union
    match = re.search(r"export type EntryType\s*=\s*(.+?);", text, re.DOTALL)
    if not match:
        sys.exit("Erro: EntryType não encontrado em types.ts")
    type_values = re.findall(r"'([^']+)'", match.group(1))

    return type_values, text

# --- Atualização do types.ts ---

def update_types_ts(value: str, label: str, code: str | None, type_values: list, text: str):
    # Adiciona ao EntryType union
    old_union = re.search(r"(export type EntryType\s*=\s*.+?;)", text, re.DOTALL).group(1)
    new_types = type_values + [value]
    new_union = "export type EntryType = " + " | ".join(f"'{v}'" for v in new_types) + ";"
    text = text.replace(old_union, new_union)

    # Formata valor do código
    code_val = f"'{code}'" if code else "null"

    # Adiciona ao ENTRY_TYPES inserindo antes do '];' final
    idx = text.rfind('\n];')
    if idx != -1:
        new_entry_line = f"\n  {{ value: '{value}', label: '{label}', code: {code_val} }},"
        text = text[:idx] + new_entry_line + text[idx:]
    else:
        print("  [AVISO] Não foi possível adicionar ao ENTRY_TYPES automaticamente")

    TYPES_TS.write_text(text)
    print(f"  [OK] src/types.ts atualizado")

# --- Criação da migration ---

def next_migration_number() -> str:
    existing = [f.name for f in MIGRATIONS_DIR.glob("[0-9][0-9][0-9]_*.sql")]
    if not existing:
        return "005"
    nums = [int(f[:3]) for f in existing]
    return str(max(nums) + 1).zfill(3)

def create_migration(value: str, label: str, code: str | None) -> Path:
    num = next_migration_number()
    slug = value.lower().replace(" ", "_").replace(".", "")
    filename = MIGRATIONS_DIR / f"{num}_add_type_{slug}.sql"
    code_sql = f"'{code}'" if code else "NULL"
    sql = f"""-- Migration {num}: Add '{value}' to tipos_lancamento
-- Generated by add_entry_type.py on {date.today()}

INSERT IGNORE INTO `tipos_lancamento` (`valor`, `label`, `codigo`)
VALUES ('{value}', '{label}', {code_sql});
"""
    filename.write_text(sql)
    print(f"  [OK] Migration criada: database/migrations/{filename.name}")
    return filename

# --- Atualização de tipos_lancamento no full_setup.sql ---

def update_tipos_lancamento_in_setup(value: str, label: str, code: str | None):
    text = FULL_SETUP_SQL.read_text()
    # Já existe?
    if f"'{value}'" in text and 'tipos_lancamento' in text[max(0, text.find(f"'{value}'")-100):text.find(f"'{value}'")+20]:
        print("  [SKIP] tipos_lancamento já contém o valor em full_setup.sql")
        return
    code_sql = f"'{code}'" if code else "NULL"
    new_line = (
        f"\nINSERT IGNORE INTO `tipos_lancamento` (`valor`, `label`, `codigo`)"
        f" VALUES ('{value}', '{label}', {code_sql});\n"
    )
    # Insere logo após o fechamento do bloco INSERT de tipos_lancamento (linha com 'TRACEJADO')
    marker = "('TRACEJADO'"
    idx = text.find(marker)
    if idx != -1:
        end = text.index(';', idx) + 1
        text = text[:end] + new_line + text[end:]
        FULL_SETUP_SQL.write_text(text)
        print("  [OK] database/full_setup.sql atualizado (tipos_lancamento)")
    else:
        print("  [AVISO] Não foi possível localizar bloco tipos_lancamento em full_setup.sql")


def get_db_connection(env: dict):
    """Cria e retorna uma conexão mysql.connector."""
    import mysql.connector
    return mysql.connector.connect(
        host=env.get("DB_HOST", "127.0.0.1"),
        port=int(env.get("DB_PORT", 3307)),
        user=env.get("DB_USER", "root"),
        password=env.get("DB_PASSWORD", "123456"),
        database=env.get("DB_NAME", "folhaponto_db"),
        charset="utf8mb4",
        collation="utf8mb4_unicode_ci",
        autocommit=True
    )

def find_docker_container() -> str | None:
    try:
        result = subprocess.run(
            ["docker", "ps", "--format", "{{.Names}}"],
            capture_output=True, text=True, timeout=5
        )
        for name in result.stdout.splitlines():
            if "mysql" in name.lower() or "mariadb" in name.lower():
                return name
    except Exception:
        pass
    return None

def apply_migration(migration_file: Path, env: dict):
    print(f"  Conectando ao banco ({env.get('DB_HOST','127.0.0.1')}:{env.get('DB_PORT','3307')})...")
    try:
        sql_content = migration_file.read_text(encoding="utf-8")
        conn = get_db_connection(env)
        cursor = conn.cursor()
        for result in cursor.execute(sql_content, multi=True):
            if result.with_rows:
                result.fetchall()
        cursor.close()
        conn.close()
        print("  [OK] Migration aplicada ao banco de dados")
    except Exception as e:
        print(f"  [ERRO] Falha ao aplicar migration via Python: {e}")
        container = find_docker_container()
        if container:
            print(f"  Tentando fallback via Docker ({container})...")
            cmd = [
                "docker", "exec", "-i", container,
                "mysql", "--default-character-set=utf8mb4",
                "-u", env["DB_USER"], f"-p{env['DB_PASSWORD']}", env["DB_NAME"]
            ]
            with open(migration_file) as f:
                result = subprocess.run(cmd, stdin=f, capture_output=True, text=True)
            if result.returncode == 0:
                print("  [OK] Migration aplicada via Docker")
            else:
                print(f"  [ERRO] Fallback Docker falhou: {result.stderr}")

# --- Main ---

def main():
    print("=" * 65)
    print("      ➕ ADICIONAR NOVO TIPO DE LANÇAMENTO NA FOLHA DE PONTO")
    print("=" * 65)

    type_values, ts_text = read_current_types()

    print("\n📌 Tipos já cadastrados no sistema:")
    for i, v in enumerate(type_values, 1):
        print(f"  {i:2}. {v}")

    print("\n" + "─" * 65)
    print("  EXPLICAÇÃO DOS CAMPOS:")
    print("  1. NOME/TEXTO DO TIPO (Identificador do Lançamento):")
    print("     Texto descritivo do lançamento que aparece nas opções da folha.")
    print("     Exemplo: LIC PATERNIDADE ART 150 LEI  ou  SUSPENSAO")
    print()
    print("  2. NOME DE EXIBIÇÃO (Label na Interface):")
    print("     Nome legível que aparece na interface (geralmente igual ao nome).")
    print("     Exemplo: LIC PATERNIDADE ART 150 LEI COMP 840/2011")
    print()
    print("  3. CÓDIGO OFICIAL (Resumo da Frequência / Página 2):")
    print("     Código numérico oficial de 5 dígitos para o Resumo da Frequência.")
    print("     Se não possuir código oficial ou não for para o resumo, deixe em branco.")
    print("     Exemplo: 00289 (para Licença Paternidade) ou 99902 (para Férias)")
    print("─" * 65 + "\n")

    value = input("1. Nome/Identificador do Lançamento (ex: LIC PATERNIDADE ART 150 LEI): ").strip().upper()
    if not value:
        sys.exit("Erro: O nome/identificador não pode ser vazio.")
    if value in type_values:
        sys.exit(f"Erro: O tipo '{value}' já existe cadastrado.")

    label = input(f"2. Nome de Exibição/Label (Pressione ENTER para usar '{value}'): ").strip().upper()
    if not label:
        label = value

    code = input("3. Código Oficial (5 dígitos ex: 00289, ou ENTER se não houver): ").strip()
    if not code:
        code = None

    print("\n" + "=" * 65)
    print("📋 CONFIRMAÇÃO DOS DADOS:")
    print(f"   • Identificador: '{value}'")
    print(f"   • Exibição (Label): '{label}'")
    print(f"   • Código Oficial:   '{code if code else 'NENHUM (null)'}'")
    print("=" * 65)

    confirm = input("Confirmar e aplicar ao sistema? (s/N): ").strip().lower()
    if confirm != "s":
        sys.exit("Operação cancelada pelo usuário.")

    print("\n🔄 Atualizando arquivos do sistema...")

    # 1. types.ts
    update_types_ts(value, label, code, type_values, ts_text)

    # 2. full_setup.sql (tipos_lancamento)
    update_tipos_lancamento_in_setup(value, label, code)

    # 3. Migration
    migration_file = create_migration(value, label, code)

    # 4. Banco de dados
    print("\n💾 Aplicando ao banco de dados...")
    env = load_env()
    apply_migration(migration_file, env)

    print("\n✅ Concluído com sucesso! Reinicie o backend se estiver em execução.")

if __name__ == "__main__":
    main()
