#!/usr/bin/env python3
"""
Sincroniza tipos de lançamento entre src/types.ts e a tabela tipos_lancamento.

O que faz:
  1. Lê todos os { value, label } do ENTRY_TYPES em src/types.ts
  2. Compara com os valores já presentes em database/full_setup.sql (tipos_lancamento)
  3. Gera e aplica INSERT IGNORE para cada tipo ausente no banco
  4. Atualiza database/full_setup.sql para manter consistência
  5. Lê os códigos não-nulos do banco e atualiza os campos `code` em src/types.ts

Seguro: usa apenas INSERT IGNORE — não apaga, não altera registros existentes.
"""

import re
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path

# Reutiliza funções e constantes do add_entry_type.py
from add_entry_type import (
    load_env,
    find_docker_container,
    apply_migration,
    update_tipos_lancamento_in_setup,
    ROOT,
    TYPES_TS,
    FULL_SETUP_SQL,
)


def parse_entry_types_from_ts() -> list[dict]:
    """Extrai todos os { value, label } do array ENTRY_TYPES em types.ts."""
    text = TYPES_TS.read_text()
    pattern = re.compile(
        r"\{\s*value:\s*'([^']+)'\s*,\s*label:\s*'([^']+)'\s*,\s*code:[^}]+\}"
    )
    return [{"value": m.group(1), "label": m.group(2)} for m in pattern.finditer(text)]


def get_tipos_in_setup() -> set[str]:
    """Retorna o conjunto de valores já presentes em tipos_lancamento no full_setup.sql."""
    text = FULL_SETUP_SQL.read_text()
    pattern = re.compile(
        r"INSERT(?:\s+IGNORE)?\s+INTO\s+`?tipos_lancamento`?[^;]+?VALUES[^;]+?'([^']+)'",
        re.DOTALL | re.IGNORECASE,
    )
    found: set[str] = set()
    for m in pattern.finditer(text):
        block = text[m.start():text.index(';', m.start()) + 1]
        for row in re.finditer(r"\(\s*'([^']+)'", block):
            found.add(row.group(1))
    return found


def create_sync_migration(missing: list[dict]) -> Path:
    """Cria um arquivo SQL de migration com INSERT IGNORE para os tipos ausentes."""
    rows = ",\n  ".join(
        f"('{t['value']}', '{t['label']}', NULL)" for t in missing
    )
    sql = f"""-- Sync migration: add missing tipos_lancamento entries
-- Generated by sync_tipos_lancamento.py on {date.today()}

INSERT IGNORE INTO `tipos_lancamento` (`valor`, `label`, `codigo`)
VALUES
  {rows};
"""
    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix="_sync_tipos_lancamento.sql",
        dir=ROOT, delete=False, prefix="sync_"
    )
    tmp.write(sql)
    tmp.close()
    return Path(tmp.name)


def query_db(sql: str, env: dict) -> list[str]:
    """Executa uma query no banco e retorna as linhas de saída no formato TSV."""
    try:
        from add_entry_type import get_db_connection
        conn = get_db_connection(env)
        cursor = conn.cursor()
        cursor.execute(sql)
        rows = cursor.fetchall()
        cursor.close()
        conn.close()
        return ["\t".join(str(val) if val is not None else "" for val in row) for row in rows]
    except Exception as e:
        print(f"  [AVISO] Erro ao consultar via Python: {e}")
        container = find_docker_container()
        if container:
            cmd = [
                "docker", "exec", "-i", container,
                "mysql", "--default-character-set=utf8mb4", "--batch", "--skip-column-names",
                "-u", env["DB_USER"], f"-p{env['DB_PASSWORD']}", env["DB_NAME"],
                "-e", sql,
            ]
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode == 0:
                return [line for line in result.stdout.splitlines() if line.strip()]
        return []


def sync_codes_to_types_ts(env: dict) -> int:
    """
    Lê códigos não-nulos de tipos_lancamento no banco e atualiza code em types.ts.
    Retorna o número de entradas atualizadas.
    """
    rows = query_db(
        "SELECT valor, codigo FROM tipos_lancamento WHERE codigo IS NOT NULL AND codigo <> '';",
        env,
    )
    if not rows:
        return 0

    text = TYPES_TS.read_text()
    updated = 0

    for row in rows:
        parts = row.split("\t")
        if len(parts) < 2:
            continue
        valor, codigo = parts[0].strip(), parts[1].strip()

        # Substitui code: null ou code: 'XXXXX' pelo código correto
        pattern = re.compile(
            r"(\{\s*value:\s*'" + re.escape(valor) + r"'\s*,\s*label:\s*'[^']*'\s*,\s*code:\s*)(null|'[^']*')(\s*\})"
        )
        new_text, n = pattern.subn(rf"\g<1>'{codigo}'\3", text)
        if n > 0 and new_text != text:
            text = new_text
            updated += 1
            print(f"  [OK] {valor} → code: '{codigo}'")

    if updated > 0:
        TYPES_TS.write_text(text)

    return updated


def main():
    print("=" * 55)
    print("  Sincronizar Tipos de Lançamento → tipos_lancamento")
    print("=" * 55)

    all_types = parse_entry_types_from_ts()
    if not all_types:
        sys.exit("Erro: Nenhum tipo encontrado em src/types.ts")

    in_setup = get_tipos_in_setup()
    missing = [t for t in all_types if t["value"] not in in_setup]

    if not missing:
        print("\n[OK] types.ts → tipos_lancamento: tudo sincronizado.")
    else:
        print(f"\nTipos ausentes em tipos_lancamento ({len(missing)}):")
        for t in missing:
            print(f"  • {t['value']}")

        print()
        confirm = input("Aplicar INSERT IGNORE no banco? (s/N): ").strip().lower()
        if confirm != "s":
            sys.exit("Cancelado.")

        migration_file = create_sync_migration(missing)
        try:
            print("\nAplicando ao banco de dados...")
            env = load_env()
            apply_migration(migration_file, env)
        finally:
            migration_file.unlink(missing_ok=True)

        print("\nAtualizando database/full_setup.sql...")
        for t in missing:
            update_tipos_lancamento_in_setup(t["value"], t["label"])

        print(f"\nConcluído! {len(missing)} tipo(s) inserido(s).")

    # Sincronização reversa: códigos do banco → types.ts
    print("\n--- Sincronizando códigos do banco → src/types.ts ---")
    env = load_env()
    n = sync_codes_to_types_ts(env)
    if n == 0:
        print("  Nenhum código novo encontrado no banco.")
    else:
        print(f"  {n} código(s) atualizado(s) em src/types.ts.")


if __name__ == "__main__":
    main()
